### PR TITLE
Allow React 18 'use client' directive

### PR DESCRIPTION
**Pull request by karlhorky**
Hi @daidodo, thanks for this and [the VS Code extension](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter)! 🙌 Amazing tools.

Currently, the new `'use client'` directive will be resorted below `import`s, causing React to not treat the file as a client component. (also will show ESLint warnings about unused expressions with rules like `@typescript-eslint/no-unused-expressions` enabled)

Reference for `'use client'`: https://github.com/reactjs/rfcs/blob/main/text/0227-server-module-conventions.md

### CODE REVIEW

**Comment by daidodo** [comment]
Thanks very much for the PR!

I have a few questions:

* Can there be multiple use-directives? E.g.:

```ts
'use strict'
'use client'

import A from 'a';
// ...
```

* Could you add [integration tests](https://github.com/daidodo/format-imports/blob/main/CONTRIBUTING.md#integration-tests-and-examples) for the new feature?

There are tests already for `'use strict'` [here](https://github.com/daidodo/format-imports/tree/main/src/test/lib/examples/shebang/use-strict). My expectation is to add a new folder for `'use client'` with similar test cases, and another folder for both directives if valid.
The folders could be like this:

```
- use/
  + strict/
  + client/
  + all/
```

**Comment by karlhorky** [comment]
> * Can there be multiple use-directives?

Good point! I didn't know this was possible. Seems like the answer is yes: https://stackoverflow.com/a/14969693/1268612

> As the [spec you linked](http://ecma-international.org/ecma-262/5.1/#sec-14.1) says,
> 
> > a `Directive Prologue` is the longest sequence of [`ExpressionStatement` productions](http://ecma-international.org/ecma-262/5.1/#sec-12.4) occurring [at the begin of a script or function] and where each [of them] consists entirely of a [`StringLiteral`](http://ecma-international.org/ecma-262/5.1/#sec-7.8.4).

So it looks like yes - you can have multiple `ExpressionStatement`s in the Directive Prologue if they are each only a `StringLiteral`.

> * Could you add [integration tests](https://github.com/daidodo/format-imports/blob/main/CONTRIBUTING.md?rgh-link-date=2022-10-28T09%3A40%3A08Z#integration-tests-and-examples) for the new feature?

Sure, will do - I'll replace the existing folder with a new `use` folder as such:

```diff
-src/test/lib/examples/shebang/use-strict
+src/test/lib/examples/shebang/use
```

And in this new `use` folder I will add 3 folders for `strict`, `client` and `all`. Or did you mean something different?

**Comment by karlhorky** [comment]
First version of the tests done in c688ebca5e93db67e2744963684bfcf565e16160, let me know if this is what you were expecting or if I should add additional cases.

**Review by daidodo — APPROVED** [review]

**Comment by karlhorky** [comment]
Thanks for the review and merge!

This will be released in `format-imports@3.2.0`, `format-imports-vscode@7.6.0` and `dozerg.tsimportsorter@7.6.0`?

**Comment by daidodo** [comment]
I've released format-imports@3.1.1 with your changes.
format-imports-vscode is on the way.

**Comment by daidodo** [comment]
I've released v7.5.1: https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter

**Pull request merged**
